In [34]:
import sys
print(sys.executable)

D:\anaconda\python.exe

In [35]:
import pandas as pd
import numpy as np

print("Python:", sys.version)
print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Python: 3.13.9 | packaged by Anaconda, Inc. | (main, Oct 21 2025, 19:09:58) [MSC v.1929 64 bit (AMD64)]
Pandas: 3.0.0
NumPy: 2.5.2

## Data Filtering and Selection

In [36]:
import numpy as np
import pandas as pd

from pandas import DataFrame

In [37]:
numbers_df = DataFrame(
    np.arange(10, 70, 2).reshape(10, 3),
    index=['sample 1', 'sample 2', 'sample 3', 'sample 4', 'sample 5',
           'sample 6', 'sample 7', 'sample 8', 'sample 9', 'sample 10'],
    columns=['feature A', 'feature B', 'feature C']
)

numbers_df

           feature A  feature B  feature C
sample 1          10         12         14
sample 2          16         18         20
sample 3          22         24         26
sample 4          28         30         32
sample 5          34         36         38
sample 6          40         42         44
sample 7          46         48         50
sample 8          52         54         56
sample 9          58         60         62
sample 10         64         66         68

In [38]:
numbers_df

           feature A  feature B  feature C
sample 1          10         12         14
sample 2          16         18         20
sample 3          22         24         26
sample 4          28         30         32
sample 5          34         36         38
sample 6          40         42         44
sample 7          46         48         50
sample 8          52         54         56
sample 9          58         60         62
sample 10         64         66         68

In [39]:
numbers_df.iloc[0,1]

np.int64(12)

In [40]:
numbers_df.iloc[0,1]=20

In [41]:
numbers_df

           feature A  feature B  feature C
sample 1          10         20         14
sample 2          16         18         20
sample 3          22         24         26
sample 4          28         30         32
sample 5          34         36         38
sample 6          40         42         44
sample 7          46         48         50
sample 8          52         54         56
sample 9          58         60         62
sample 10         64         66         68

In [42]:
numbers_df.iloc[[1,2,4],[1,2]]

          feature B  feature C
sample 2         18         20
sample 3         24         26
sample 5         36         38

#### Comparison operators (> < = <= => == !=) and Masking.

Create a boolean mask to identify values greater than 42

In [43]:
mask = numbers_df > 42
mask

           feature A  feature B  feature C
sample 1       False      False      False
sample 2       False      False      False
sample 3       False      False      False
sample 4       False      False      False
sample 5       False      False      False
sample 6       False      False       True
sample 7        True       True       True
sample 8        True       True       True
sample 9        True       True       True
sample 10       True       True       True

In [44]:
numbers_df[mask]

           feature A  feature B  feature C
sample 1         NaN        NaN        NaN
sample 2         NaN        NaN        NaN
sample 3         NaN        NaN        NaN
sample 4         NaN        NaN        NaN
sample 5         NaN        NaN        NaN
sample 6         NaN        NaN       44.0
sample 7        46.0       48.0       50.0
sample 8        52.0       54.0       56.0
sample 9        58.0       60.0       62.0
sample 10       64.0       66.0       68.0

In [47]:
numbers_df[numbers_df>42]=0
numbers_df

           feature A  feature B  feature C
sample 1          10         20         14
sample 2          16         18         20
sample 3          22         24         26
sample 4          28         30         32
sample 5          34         36         38
sample 6          40         42          0
sample 7           0          0          0
sample 8           0          0          0
sample 9           0          0          0
sample 10          0          0          0

Select rows 3 to 6 and columns 2 to 3 using integer positions

In [48]:
numbers_df.iloc[2:6,1:3]

          feature B  feature C
sample 3         24         26
sample 4         30         32
sample 5         36         38
sample 6         42          0