## Working with Missing Data in Pandas

In [2]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [3]:
data = {
    'name': ['Anna', 'Tom', 'Emily', 'David', 'Laura', 'James', 'Sophie'],
    'age': [25, 31, 28, 35, 29, 33, 27],
    'department': ['Sales', 'IT', 'HR', 'Finance', 'IT', 'Sales', 'HR'],
    'score': [78, 91, 85, 74, 88, 80, 95]
}

employees_df = DataFrame(data)

# Add missing values to some cells for practice
employees_df.iloc[2:5, 1] = np.nan
employees_df.iloc[3:6, 3] = np.nan
employees_df.iloc[3, :] = np.nan

employees_df

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily   NaN         HR   85.0
3     NaN   NaN        NaN    NaN
4   Laura   NaN         IT    NaN
5   James  33.0      Sales    NaN
6  Sophie  27.0         HR   95.0

In [4]:
# Check which values are missing
employees_df.isnull()

    name    age  department  score
0  False  False       False  False
1  False  False       False  False
2  False   True       False  False
3   True   True        True   True
4  False   True       False   True
5  False  False       False   True
6  False  False       False  False

In [5]:
# Check which values are not missing
employees_df.notnull()

    name    age  department  score
0   True   True        True   True
1   True   True        True   True
2   True  False        True   True
3  False  False       False  False
4   True  False        True  False
5   True   True        True  False
6   True   True        True   True

In [6]:
# Create a boolean Series showing where values in the age column are missing
bool_series = pd.isnull(employees_df['age'])

# Display only rows where age is missing
employees_df[bool_series]

    name  age department  score
2  Emily  NaN         HR   85.0
3    NaN  NaN        NaN    NaN
4  Laura  NaN         IT    NaN

In [7]:
# Replace all missing values with 0
employees_df.fillna(0)

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily   0.0         HR   85.0
3       0   0.0          0    0.0
4   Laura   0.0         IT    0.0
5   James  33.0      Sales    0.0
6  Sophie  27.0         HR   95.0

Fill missing values using the previous valid observation

In [8]:
employees_df.ffill()

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily  31.0         HR   85.0
3   Emily  31.0         HR   85.0
4   Laura  31.0         IT   85.0
5   James  33.0      Sales   85.0
6  Sophie  27.0         HR   95.0

Fill missing values using the next valid observation

In [9]:
employees_df.bfill()

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily  33.0         HR   85.0
3   Laura  33.0         IT   95.0
4   Laura  33.0         IT   95.0
5   James  33.0      Sales   95.0
6  Sophie  27.0         HR   95.0

Fill missing values in 'rank' using linear interpolation

In [10]:
employees_df['score'] = employees_df['score'].interpolate(method='linear')

employees_df

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily   NaN         HR   85.0
3     NaN   NaN        NaN   87.5
4   Laura   NaN         IT   90.0
5   James  33.0      Sales   92.5
6  Sophie  27.0         HR   95.0

In [11]:
# Remove rows containing at least one missing value
employees_df.dropna()

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
5   James  33.0      Sales   92.5
6  Sophie  27.0         HR   95.0

In [12]:
# Remove rows only if all values in the row are missing
employees_df.dropna(how='all')

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
2   Emily   NaN         HR   85.0
3     NaN   NaN        NaN   87.5
4   Laura   NaN         IT   90.0
5   James  33.0      Sales   92.5
6  Sophie  27.0         HR   95.0

In [13]:
# Remove columns containing missing values
employees_df.dropna(axis=1)

   score
0   78.0
1   91.0
2   85.0
3   87.5
4   90.0
5   92.5
6   95.0

In [14]:
# Remove rows containing missing values
employees_df.dropna(axis=0)

     name   age department  score
0    Anna  25.0      Sales   78.0
1     Tom  31.0         IT   91.0
5   James  33.0      Sales   92.5
6  Sophie  27.0         HR   95.0