## Working with Missing Data in Pandas

In [1]:
import numpy as np
import pandas as pd

from pandas import DataFrame

### Filling missing values using fillna(), replace() and interpolate()

In [26]:
data = {'names':['steve','john','richard','sarah','randy','micheal','julie'],
        'age':[20,22,20,21,24,23,22],
        'gender':['Male','Male','Male','Female','Male','Male','Female'],
        'rank':[2,1,4,5,3,7,6]}

ranking_df = DataFrame(data)
ranking_df.iloc[2:5,1]= np.nan
ranking_df.iloc[3:6,3]= np.nan
ranking_df.iloc[3,:]= np.nan
ranking_df

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
3      NaN   NaN     NaN   NaN
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [27]:
ranking_df.isnull()

   names    age  gender   rank
0  False  False   False  False
1  False  False   False  False
2  False   True   False  False
3   True   True    True   True
4  False   True   False   True
5  False  False   False   True
6  False  False   False  False

In [28]:
ranking_df.notnull()

   names    age  gender   rank
0   True   True    True   True
1   True   True    True   True
2   True  False    True   True
3  False  False   False  False
4   True  False    True  False
5   True   True    True  False
6   True   True    True   True

In [29]:
bool_series = pd.isnull(ranking_df['age'])
ranking_df[bool_series]

     names  age gender  rank
2  richard  NaN   Male   4.0
3      NaN  NaN    NaN   NaN
4    randy  NaN   Male   NaN

In [30]:
ranking_df.fillna(0)

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   0.0    Male   4.0
3        0   0.0       0   0.0
4    randy   0.0    Male   0.0
5  micheal  23.0    Male   0.0
6    julie  22.0  Female   6.0

Fill missing values using the previous valid observation

In [31]:
ranking_df.ffill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  22.0    Male   4.0
3  richard  22.0    Male   4.0
4    randy  22.0    Male   4.0
5  micheal  23.0    Male   4.0
6    julie  22.0  Female   6.0

Fill missing values using the next valid observation

In [32]:
ranking_df.bfill()

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard  23.0    Male   4.0
3    randy  23.0    Male   6.0
4    randy  23.0    Male   6.0
5  micheal  23.0    Male   6.0
6    julie  22.0  Female   6.0

Fill missing values in 'rank' using linear interpolation

In [23]:
rank_df = ranking_df['rank'].interpolate(method='linear')
ranking_df

     names    age  gender  rank
0    steve  20.00    Male   2.0
1     john  22.00    Male   1.0
2  richard  22.25    Male   4.0
3      NaN  22.50     NaN   4.5
4    randy  22.75    Male   5.0
5  micheal  23.00    Male   5.5
6    julie  22.00  Female   6.0

In [33]:
ranking_df.dropna()

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0

In [34]:
ranking_df.dropna(how='all')

     names   age  gender  rank
0    steve  20.0    Male   2.0
1     john  22.0    Male   1.0
2  richard   NaN    Male   4.0
4    randy   NaN    Male   NaN
5  micheal  23.0    Male   NaN
6    julie  22.0  Female   6.0

In [35]:
ranking_df.dropna(axis=1)

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6]

In [36]:
ranking_df.dropna(axis=0)

   names   age  gender  rank
0  steve  20.0    Male   2.0
1   john  22.0    Male   1.0
6  julie  22.0  Female   6.0