In [1]:
import pandas as pd

# Removing Duplicate Data in Pandas

Duplicate records can affect data quality and lead to incorrect analysis.
In this example, I practise identifying and removing duplicate customer records.

In [2]:
customers_df = pd.DataFrame({
    'customer_id': [101, 101, 102, 102, 103, 103, 103],
    'name': ['Emma', 'Emma', 'Noah', 'Noah', 'Olivia', 'Olivia', 'Olivia'],
    'city': ['London', 'London', 'Manchester', 'Manchester',
             'Birmingham', 'Birmingham', 'Birmingham']
})

customers_df

   customer_id    name        city
0          101    Emma      London
1          101    Emma      London
2          102    Noah  Manchester
3          102    Noah  Manchester
4          103  Olivia  Birmingham
5          103  Olivia  Birmingham
6          103  Olivia  Birmingham

### Identifying duplicate rows

`duplicated()` checks whether a row has already appeared in the DataFrame.
It returns `True` for duplicate rows and `False` for unique rows.

In [6]:
# Check which rows are duplicates
customers_df.duplicated()

0    False
1     True
2    False
3     True
4    False
5     True
6     True
dtype: bool

In [7]:
# Count the total number of duplicate rows
customers_df.duplicated().sum()

np.int64(4)

### Removing exact duplicates

`drop_duplicates()` removes rows where all values are duplicated.
By default, Pandas keeps the first occurrence.

In [11]:
customers_df.drop_duplicates()

   customer_id    name        city
0          101    Emma      London
2          102    Noah  Manchester
4          103  Olivia  Birmingham

In [13]:
clean_customers_df = customers_df.drop_duplicates()

clean_customers_df

   customer_id    name        city
0          101    Emma      London
2          102    Noah  Manchester
4          103  Olivia  Birmingham

In [14]:
customer_records = pd.DataFrame({
    'customer_id': [101, 101, 102, 102, 103, 103, 104],
    'name': ['Emma', 'Emma', 'Noah', 'Noah', 'Olivia', 'Olivia', 'Liam'],
    'city': ['London', 'London', 'Manchester', 'Leeds',
             'Birmingham', 'Birmingham', 'Oxford']
})

customer_records

   customer_id    name        city
0          101    Emma      London
1          101    Emma      London
2          102    Noah  Manchester
3          102    Noah       Leeds
4          103  Olivia  Birmingham
5          103  Olivia  Birmingham
6          104    Liam      Oxford

In [15]:
customer_records.drop_duplicates()

   customer_id    name        city
0          101    Emma      London
2          102    Noah  Manchester
3          102    Noah       Leeds
4          103  Olivia  Birmingham
6          104    Liam      Oxford

In [16]:
# Remove duplicates based only on customer_id
unique_customers = customer_records.drop_duplicates(subset=['customer_id'])

unique_customers

   customer_id    name        city
0          101    Emma      London
2          102    Noah  Manchester
4          103  Olivia  Birmingham
6          104    Liam      Oxford